services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.05.0
    hostname: 'Raspberry Pi 4'
    environment:
      TZ: 'Europe/Berlin'
      WEBTHEME: 'default-darker'
      VIRTUAL_HOST: 'pihole'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
    volumes:
      - pihole_etc:/etc/pihole
      - dnsmasq_etc:/etc/dnsmasq.d
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.rpi.local`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
networks:
  traefik_proxy:
    external: true
volumes:
  pihole_etc:
    driver: local
  dnsmasq_etc:
    driver: local
